### ISSUE TITLE
How can i save the state of a progress bar?

### ISSUE THREAD

**Issue by mattia56** [MattisBrizard/circular_countdown#4]
If i change the screen, the progress bar restarts

**Comment by MattisBrizard** [comment]
Hey 👋 

Thanks for using the package.

If your need is to have a TimeCircularCountdown that has the same state between two screens, it is possible but not in a reliable way. In fact as the timer logic is located in the widget, when you dispose it by navigating to another page, you also dispose the inner timer. So one way could be to store the value of the timer on each changes and pass It to the next page to start at this value but it’s not really reliable because the time between the previous timer update and the navigation is lost, meaning you could have this flow :
15s
14s
*500 ms* then navigating

So you’ll start the new Countdown at 14 while 500 ms have already passed.

To have something 100% reliable I would recommend to implement your own timer logic located in an object that is not disposed across screens, and a simple CircularCountdown that only consumes the data of your Timer object.

I'm actively thinking of creating a TimerController object that would be passed to the TimeCircularCountdown and so the timer logic would be separated from the widget itself.

Tell me if it answers your issue.

Mattis

**Comment by myThorsten** [comment]
Hello :)

Does that mean that the timer is also reset when rotating the screen?

**Comment by MattisBrizard** [comment]
Hello @myThorsten  😃 
Normally not, rotating the screen imply just a rebuild of the widget, you don't dispose it.

**Comment by MattisBrizard** [comment]
Hi @mattia56, i just published a new package: timer_controller
Github: https://github.com/MattisBrizard/timer_controller
Pub: https://pub.dev/packages/timer_controller

This can be used in addition to circular_countdown to have more fine-grained controls about the timer. And easily deal with a single timer object across differents screens for example.

I'm closing this issue, if you need help to build something with this new package, just tell me and I'll try to help you :)
